CREATE TABLE EMPLOYEES(ID INTEGER PRIMARY KEY, NAME VARCHAR(40), POSITION VARCHAR(30), SALARY NUMERIC)

ALTER TABLE EMPLOYEES ADD COLUMN HIREDATE DATE;

SELECT * FROM EMPLOYEES

ALTER TABLE EMPLOYEES ALTER COLUMN SALARY TYPE INTEGER

ALTER TABLE EMPLOYEES DROP COLUMN HIREDATE;

ALTER TABLE EMPLOYEES RENAME TO NEW_EMPLOYEES

SELECT * FROM NEW_EMPLOYEES

ALTER TABLE NEW_EMPLOYEES RENAME COLUMN SALARY TO MONEY

INSERT INTO NEW_EMPLOYEES (ID, NAME, POSITION, MONEY)
VALUES(1,"JOHN", "SD",60000),
(2,"HARINI","TE",500)